version: '3.7'

services:
  django:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/django-project/static
    ports:
      - "8000:8000"
    command: [ "daphne", "-p", "8000", "beam.asgi:application", "-b", "0.0.0.0" ]
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - django

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

volumes:
  static_volume:
